name: OSX

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

jobs:
  build-osx:

    name: OSX Sudoku
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install conda dependencies
      run: |
        conda env update --file ${{github.workspace}}/configuration/sudoku_env.yml --name sudoku_env

    - name: Python Test
      working-directory: ${{github.workspace}}
      run: |
        conda install pytest
        python -m pytest ${{github.workspace}}/python/tests

    - name: archive error 1
      uses: actions/upload-artifact@v3
      if: always()
      continue-on-error: true
      with:
        name: osx-CMakeOutput.log
        path: ${{github.workspace}}/build/CMakeFiles/CMakeOutput.log

    - name: archive error 2
      uses: actions/upload-artifact@v3
      if: always()
      continue-on-error: true
      with:
        name: osx-CMakeError.log
        path: ${{github.workspace}}/build/CMakeFiles/CMakeError.log
